services:
  coordinator:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./src:/app/src
    networks:
      - strands-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - coordinator
    networks:
      - strands-network

networks:
  strands-network:
    driver: bridge