services:
  test-coordinator:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - PYTHONPATH=/app
      - NODE_ENV=test
    volumes:
      - ./test-results:/app/test-results
    command: pytest tests/ --junitxml=test-results/test-results.xml --cov=src --cov-report=xml:test-results/coverage.xml
    networks:
      - test-network

  test-frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - ./frontend/test-results:/app/test-results
    command: sh -c "npm install && npm run test:coverage && npm run lint"
    environment:
      - NODE_ENV=test
    networks:
      - test-network

  e2e-tests:
    image: mcr.microsoft.com/playwright:v1.40.0-focal
    working_dir: /app
    volumes:
      - ./frontend:/app
      - ./frontend/test-results:/app/test-results
    command: sh -c "npm install && npm run e2e"
    environment:
      - NODE_ENV=test
    depends_on:
      - test-coordinator
    networks:
      - test-network

networks:
  test-network:
    driver: bridge