services:
  coordinator:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - DEBUG=${DEBUG:-true}
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
      - NODE_ENV=${NODE_ENV:-development}
      - API_BASE_URL=${API_BASE_URL:-http://coordinator:8000}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000}
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    networks:
      - strands-network

  frontend:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - API_BASE_URL=${API_BASE_URL:-http://coordinator:8000}
      - FRONTEND_URL=${FRONTEND_URL:-http://frontend:3000}
    depends_on:
      - coordinator
    networks:
      - strands-network

networks:
  strands-network:
    driver: bridge