services:
  coordinator:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./src:/app/src
    networks:
      - strands-network

  frontend:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - VITE_API_URL=http://coordinator:8000
    depends_on:
      - coordinator
    networks:
      - strands-network

networks:
  strands-network:
    driver: bridge